# Generated by uniffi-bindgen-react-native
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))
folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -Wno-comma -Wno-shorten-64-to-32'

Pod::Spec.new do |s|
  s.name         = "ReactNativeMatrixSdk"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => min_ios_version_supported }
  s.source       = { :git => "https://github.com/unomed-dev/react-native-matrix-sdk.git", :tag => "#{s.version}" }

  s.source_files = "ios/**/*.{h,m,mm,swift}", "ios/generated/**/*.{h,m,mm}", "cpp/**/*.{hpp,cpp,c,h}", "cpp/generated/**/*.{hpp,cpp,c,h}"

  # From React Native 0.86 on, codegen writes app-level scaffolding into the same
  # output directory as this package's TurboModule spec: a Package.swift for SPM,
  # the RCTAppDependencyProvider, and the RCTModuleProviders family. All of that
  # belongs to the app - its own ReactCodegen and ReactAppDependencyProvider pods
  # build those exact files - so the globs above must not sweep them in here.
  #
  # Package.swift is the one that breaks the build outright rather than merely
  # duplicating. A single .swift file makes this a mixed Swift/ObjC pod, so Clang
  # has to build the Objective-C module for Swift to import it - and it does that
  # in Objective-C mode, not Objective-C++. The umbrella header reaches the Fabric
  # event emitter headers, which `#include <memory>`, and the build dies with:
  #
  #   React-Fabric/react/renderer/components/view/BaseViewEventEmitter.h:10:10:
  #   error: 'memory' file not found
  #   error: could not build Objective-C module 'ReactNativeMatrixSdk'
  #
  # Up to 0.76 codegen emitted no Swift here at all, so the pod was pure ObjC/C++
  # and the question never arose.
  s.exclude_files = "ios/generated/Package.swift",
                    "ios/generated/ReactAppDependencyProvider/**/*",
                    "ios/generated/ReactCodegen/RCT*.{h,mm}"

  s.vendored_frameworks = "build/RnMatrixRustSdk.xcframework"
  s.dependency    "uniffi-bindgen-react-native", "0.31.0-2"

  # Use install_modules_dependencies helper to install the dependencies if React Native version >=0.71.0.
  # See https://github.com/facebook/react-native/blob/febf6b7f33fdb4904669f99d795eba4c0f95d7bf/scripts/cocoapods/new_architecture.rb#L79.
  if respond_to?(:install_modules_dependencies, true)
    install_modules_dependencies(s)
  else
    s.dependency "React-Core"

    # Don't install the dependencies when we run `pod install` in the old architecture.
    if ENV['RCT_NEW_ARCH_ENABLED'] == '1' then
      s.compiler_flags = folly_compiler_flags + " -DRCT_NEW_ARCH_ENABLED=1"
      s.pod_target_xcconfig    = {
          "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/boost\"",
          "OTHER_CPLUSPLUSFLAGS" => "-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1",
          "CLANG_CXX_LANGUAGE_STANDARD" => "c++17"
      }
      s.dependency "React-Codegen"
      s.dependency "RCT-Folly"
      s.dependency "RCTRequired"
      s.dependency "RCTTypeSafety"
      s.dependency "ReactCommon/turbomodule/core"
    end
  end
end