#!/usr/bin/env node
/*
 * Re-add this package's `s.exclude_files` after code generation.
 *
 * The podspec is generated by uniffi-bindgen-react-native from
 * `crates/ubrn_cli/templates/jsi/ios/module-template.podspec`, so it is rewritten
 * on every `yarn generate:ios` and cannot hold a hand-edit - the same situation as
 * android/proguard-rules.pro, see scripts/append-proguard-rules.js.
 *
 * Must run BEFORE `pod install`, which reads the podspec. It is wired into
 * `ubrn:ios:post-process` ahead of that step for exactly that reason.
 *
 * Not contributed to ubrn's template: `s.source_files` there is generic, and what
 * has to be excluded depends on which React Native version the consuming app
 * builds with, not on anything ubrn knows.
 *
 * Idempotent - running it twice is a no-op.
 */

const fs = require('fs');
const path = require('path');

// Anchor. The generated podspec goes straight from this line to
// `s.vendored_frameworks`; the exclusions belong between the two.
const SOURCE_FILES_PATTERN = /^(\s*)s\.source_files\s*=.*$/m;

const MARKER = 's.exclude_files';

// The leading and trailing newlines are both load-bearing. In the generated
// podspec `s.source_files` and `s.vendored_frameworks` are adjacent with no blank
// line between them, so this block has to supply the blank line on each side of
// itself. Verify any change to this against real generated output - e.g.
// `git show <upstream>:ReactNativeMatrixSdk.podspec` - and not against the
// committed file with this block deleted, which begs the question.
const EXCLUDES = `
  # From React Native 0.86 on, codegen writes app-level scaffolding into the same
  # output directory as this package's TurboModule spec: a Package.swift for SPM,
  # the RCTAppDependencyProvider, and the RCTModuleProviders family. All of that
  # belongs to the app - its own ReactCodegen and ReactAppDependencyProvider pods
  # build those exact files - so the globs above must not sweep them in here.
  #
  # Package.swift is the one that breaks the build outright rather than merely
  # duplicating. A single .swift file makes this a mixed Swift/ObjC pod, so Clang
  # has to build the Objective-C module for Swift to import it - and it does that
  # in Objective-C mode, not Objective-C++. The umbrella header reaches the Fabric
  # event emitter headers, which \`#include <memory>\`, and the build dies with:
  #
  #   React-Fabric/react/renderer/components/view/BaseViewEventEmitter.h:10:10:
  #   error: 'memory' file not found
  #   error: could not build Objective-C module 'ReactNativeMatrixSdk'
  #
  # Up to 0.76 codegen emitted no Swift here at all, so the pod was pure ObjC/C++
  # and the question never arose.
  s.exclude_files = "ios/generated/Package.swift",
                    "ios/generated/ReactAppDependencyProvider/**/*",
                    "ios/generated/ReactCodegen/RCT*.{h,mm}"
`;

/**
 * @returns {string} Path to the single podspec at the repository root
 */
function findPodspec() {
  const root = path.resolve(__dirname, '..');
  const found = fs.readdirSync(root).filter((entry) => entry.endsWith('.podspec'));

  if (found.length !== 1) {
    console.error(
      `Error: expected exactly one .podspec at ${root}, found ${found.length}` +
        (found.length > 0 ? `: ${found.join(', ')}` : '')
    );
    process.exit(1);
  }

  return path.join(root, found[0]);
}

function patchPodspec() {
  const filePath = findPodspec();
  const contents = fs.readFileSync(filePath, 'utf8');
  const name = path.basename(filePath);

  if (contents.includes(MARKER)) {
    console.log('patch-podspec: exclude_files already present, nothing to do');
    return;
  }

  if (!SOURCE_FILES_PATTERN.test(contents)) {
    console.error(`Error: no \`s.source_files =\` line in ${name} to anchor to`);
    process.exit(1);
  }

  fs.writeFileSync(
    filePath,
    contents.replace(SOURCE_FILES_PATTERN, (line) => `${line}\n${EXCLUDES}`)
  );

  console.log(`patch-podspec: added exclude_files to ${name}`);
}

patchPodspec();
